management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
  observations:
    annotations:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
    export:
      otlp:
        enabled: ${app.otel.enabled:false}
  logging:
    export:
      otlp:
        enabled: ${app.otel.enabled:false}
  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: ${app.otel.endpoint:http://localhost:4318}/v1/logs
          headers:
            Authorization: ${app.otel.auth.header.value:none}
    tracing:
      export:
        otlp:
          endpoint: ${app.otel.endpoint:http://localhost:4318}/v1/traces
          headers:
            Authorization: ${app.otel.auth.header.value:none}
  otlp:
    metrics:
      export:
        enabled: ${app.otel.enabled:false}
        url: ${app.otel.endpoint:http://localhost:4318}/v1/metrics
        headers:
          Authorization: ${app.otel.auth.header.value:none}

spring:
  application:
    name: spec-forge-api
  jackson:
    default-property-inclusion: non_empty