name: "CD (prod:spec-forge-api)"

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: volodymyr-oleksiienko/spec-forge-api
  VERSION: ${{ github.ref_name }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'corretto'
          cache: 'maven'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Install Dependencies
        run: mvn clean install -DskipTests

      - name: Build Docker Image
        run: |
          mvn spring-boot:build-image -pl spec-forge-api-infra \
            -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} \
            -Dspring-boot.build-image.tags=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker Images to Registry
        run: docker push -a ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Copy Compose File to Server
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/opt/backend"

      - name: Execute Remote Deployment
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GITHUB_ACTOR, VERSION
          script: |
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
            cd /opt/backend
            echo "APP_VERSION=$VERSION" > .env
            docker compose pull
            docker compose up -d
            docker system prune -a -f